# Generated by Django 4.0.3 on 2022-05-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_nemae', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=11)),
                ('dentestry', models.CharField(max_length=30)),
            ],
        ),
    ]
