# Generated by Django 4.0.3 on 2022-05-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='available_time',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
