# Generated by Django 4.0.3 on 2022-05-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_booking_available_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dentestry',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_nemae',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
