# Generated by Django 4.0.3 on 2022-05-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_alter_booking_dentestry_alter_booking_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='available_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
