# Generated by Django 4.0.3 on 2022-05-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_rename_dentestry_booking_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='last_nemae',
            new_name='last_name',
        ),
    ]
