# Generated by Django 4.0.3 on 2022-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0006_rename_last_nemae_booking_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('speciality', models.CharField(max_length=30)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('attendance_day', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
