# Generated by Django 4.0.3 on 2022-06-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0007_doctor_alter_booking_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
