# Generated by Django 4.0.3 on 2022-06-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0008_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='doctor_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='num_of_bulding',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='attendance_day',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
