# Generated by Django 4.0.3 on 2022-06-16 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0009_clinic_doctor_name_clinic_num_of_bulding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clininfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='bookingapp.clinic')),
            ],
        ),
    ]
