# Generated by Django 4.0.3 on 2022-06-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0010_clininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clininfo',
            name='doctor_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clininfo',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clininfo',
            name='num_of_bulding',
            field=models.IntegerField(null=True),
        ),
    ]
