# Generated by Django 4.0.3 on 2022-06-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0012_alter_clininfo_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clininfo',
            name='name',
        ),
    ]
