# Generated by Django 4.0.3 on 2022-06-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0013_remove_clininfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='num_of_bulding',
        ),
    ]
