# Generated by Django 4.0.3 on 2022-06-17 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0014_remove_clinic_doctor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='num_of_building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.clinic')),
            ],
        ),
    ]
