# Generated by Django 4.0.3 on 2022-06-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0016_num_of_building_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='num_of_building',
            name='name',
        ),
    ]
