# Generated by Django 4.0.3 on 2022-06-17 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0017_remove_num_of_building_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clininfo',
            name='doctor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.doctor'),
        ),
    ]
