# Generated by Django 4.0.3 on 2022-06-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0020_num_of_building_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='num_of_building',
            name='name',
        ),
        migrations.AlterField(
            model_name='clininfo',
            name='doctor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.doctor'),
        ),
        migrations.AlterField(
            model_name='clininfo',
            name='num_of_bulding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.num_of_building'),
        ),
        migrations.AlterField(
            model_name='num_of_building',
            name='num',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
